from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register the viewsets with it.
# This automatically generates the URLs for the Recipe and Tag viewsets.
router = DefaultRouter()
router.register("recipes", views.RecipeViewSet)
router.register("tags", views.TagViewSet)
router.register("ingredient", views.IngredientViewSet)

app_name = "recipe"

# Define the URL patterns to include the automatically generated URLs from the router.
urlpatterns = [
    path("", include(router.urls)),  # Include all the URLs generated by the router
]
